%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.5

-ifndef(test_pb_pb).
-define(test_pb_pb, true).

-define(test_pb_pb_gpb_version, "3.26.5").

-ifndef('CONTENT_PB_H').
-define('CONTENT_PB_H', true).
-record(content,
        {name                   :: integer(),       % = 1, 32 bits
         code                   :: binary() | iolist() % = 2
        }).
-endif.

-ifndef('GET_INFO_PB_H').
-define('GET_INFO_PB_H', true).
-record(get_info,
        {content                :: #content{}       % = 1
        }).
-endif.

-endif.
