%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.5

-ifndef(test_pb_pb).
-define(test_pb_pb, true).

-define(test_pb_pb_gpb_version, "3.26.5").

-ifndef('CONTENT_PB_H').
-define('CONTENT_PB_H', true).
-record(content,
        {name                   :: binary() | iolist() | undefined, % = 1
         code = []              :: [integer()]      % = 2, 32 bits
        }).
-endif.

-endif.
